export interface EquipmentItem {
  id: string;
  name: string;
  jpName: string;
  description: string;
  type: "weapon" | "armor";
  cost: number;
  attackBonus: number;
  magicBonus: number;
  defenseBonus: number;
}

export const EQUIPMENT_ITEMS: EquipmentItem[] = [
  // --- WEAPONS ---
  {
    id: "bronze_dagger",
    name: "Bronze Dagger",
    jpName: "青銅の短剣",
    description: "安価だが鋭い刃。手軽に攻撃力を高められる初心者の武器。",
    type: "weapon",
    cost: 80,
    attackBonus: 6,
    magicBonus: 0,
    defenseBonus: 0,
  },
  {
    id: "aether_wand",
    name: "Aether Wand",
    jpName: "エーテルの杖",
    description: "魔導水晶が組み込まれた杖。呪文威力が大きく増加する。",
    type: "weapon",
    cost: 150,
    attackBonus: 3,
    magicBonus: 12,
    defenseBonus: 0,
  },
  {
    id: "iron_saber",
    name: "Iron Saber",
    jpName: "鉄のサーベル",
    description: "軍用としても広く普及している鍛鉄製のサーベル。扱いやすく堅実。",
    type: "weapon",
    cost: 480,
    attackBonus: 14,
    magicBonus: 0,
    defenseBonus: 0,
  },
  {
    id: "runic_staff",
    name: "Runic Staff",
    jpName: "ルーンの魔導杖",
    description: "精霊の刻印を彫り込んだ木製の魔導杖。術者の精神力を増幅し魔法攻撃に優れる。",
    type: "weapon",
    cost: 850,
    attackBonus: 5,
    magicBonus: 22,
    defenseBonus: 1,
  },
  {
    id: "heavy_halberd",
    name: "Heavy Halberd",
    jpName: "重騎士のハルバード",
    description: "斧と槍の特性を兼ね備えた長柄武器。重量に見合う物理破壊力を誇る。",
    type: "weapon",
    cost: 1250,
    attackBonus: 26,
    magicBonus: 0,
    defenseBonus: 2,
  },
  {
    id: "meteor_sword",
    name: "Meteor Sword",
    jpName: "星屑の直剣メテオ",
    description: "隕石から取れた希土類を用いた美しい剣。高速な一撃と星屑の加護を持つ。",
    type: "weapon",
    cost: 1850,
    attackBonus: 34,
    magicBonus: 10,
    defenseBonus: 0,
  },
  {
    id: "celestial_wand",
    name: "Celestial Wand",
    jpName: "天輝の魔導書",
    description: "失われた古代の英知を秘めた魔導書。莫大な魔導エネルギーをプレイヤーに宿す。",
    type: "weapon",
    cost: 2500,
    attackBonus: 6,
    magicBonus: 45,
    defenseBonus: 2,
  },
  {
    id: "dragon_lance",
    name: "Dragon Lance",
    jpName: "屠竜の獄槍ドラゴナス",
    description: "大公国一の鍛冶師が竜狩りのために鍛え上げた漆黒の凶槍。",
    type: "weapon",
    cost: 3800,
    attackBonus: 52,
    magicBonus: 0,
    defenseBonus: 4,
  },
  {
    id: "chronos_scythe",
    name: "Chronos Scythe",
    jpName: "刻守の外鎌クロノス",
    description: "時を管理する番人が用いると言われる大鎌。空間すら引き裂く刃を有する。",
    type: "weapon",
    cost: 5200,
    attackBonus: 65,
    magicBonus: 28,
    defenseBonus: 3,
  },
  {
    id: "asylum_blade",
    name: "Asylum Dark Blade",
    jpName: "暗黒魔剣アサイラム",
    description: "冥界の闇エネルギーを宿した魔導大剣。物理と魔法の両力を極限まで高める。",
    type: "weapon",
    cost: 7500,
    attackBonus: 82,
    magicBonus: 45,
    defenseBonus: 10,
  },
  {
    id: "valkyrie_spear",
    name: "Valkyrie Spear",
    jpName: "聖槍ヴァルキリー",
    description: "戦乙女が愛用したとされる黄金の槍。物理攻撃と魔法適性が高次元で調和している。",
    type: "weapon",
    cost: 11000,
    attackBonus: 105,
    magicBonus: 30,
    defenseBonus: 5,
  },
  {
    id: "genesis_scepter",
    name: "Genesis Scepter",
    jpName: "創世王の智杖ジェネシス",
    description: "神聖な結晶が埋め込まれた秘杖。詠唱される全ての魔法ダメージを極大化する。",
    type: "weapon",
    cost: 16000,
    attackBonus: 40,
    magicBonus: 140,
    defenseBonus: 8,
  },
  {
    id: "antigravity_blade",
    name: "Antigravity Blade",
    jpName: "反重力神剣グラビティ",
    description: "時空歪曲テクノロジーの真髄とも言える神剣。凄まじい威力を生み出す。",
    type: "weapon",
    cost: 24000,
    attackBonus: 185,
    magicBonus: 110,
    defenseBonus: 20,
  },
  {
    id: "ragnarok_calamity",
    name: "Ragnarok Calamity",
    jpName: "終焉魔剣ラグナロク",
    description: "世界の破滅を暗示する絶対魔武器。これに選ばれし者は万物の支配者たり得る。",
    type: "weapon",
    cost: 35000,
    attackBonus: 260,
    magicBonus: 180,
    defenseBonus: 30,
  },
  {
    id: "antimatter_edge",
    name: "Antimatter Edge",
    jpName: "反物質光刃アナイアレイター",
    description: "触れた物質を対消滅させる禁忌の戦術光学刃。極限の戦闘出力を約束する。",
    type: "weapon",
    cost: 55000,
    attackBonus: 380,
    magicBonus: 260,
    defenseBonus: 50,
  },

  // --- ARMORS ---
  {
    id: "leather_vest",
    name: "Leather Vest",
    jpName: "旅人の皮ベスト",
    description: "なめし皮で作られた頑丈なベスト。動きやすさに優れる。",
    type: "armor",
    cost: 60,
    attackBonus: 0,
    magicBonus: 0,
    defenseBonus: 4,
  },
  {
    id: "iron_plate",
    name: "Iron Plate Mail",
    jpName: "鉄のプレートメイル",
    description: "分厚い鉄板で作られた鎧。重い一撃から身をしっかり守る。",
    type: "armor",
    cost: 320,
    attackBonus: 0,
    magicBonus: 0,
    defenseBonus: 10,
  },
  {
    id: "silver_chainmail",
    name: "Silver Chainmail",
    jpName: "白銀のチェインメイル",
    description: "細かく編み込まれたミスリル銀の鎖帷子。物理防御力に加え魔法耐性も上昇する。",
    type: "armor",
    cost: 750,
    attackBonus: 0,
    magicBonus: 4,
    defenseBonus: 18,
  },
  {
    id: "mage_robes",
    name: "Mage Robes",
    jpName: "魔導術士の羽衣",
    description: "対魔術繊維で織られた機能的な衣。着用するだけで魔力が湧き出る。",
    type: "armor",
    cost: 1500,
    attackBonus: 0,
    magicBonus: 18,
    defenseBonus: 24,
  },
  {
    id: "sage_cloak",
    name: "Scholar & Sage Cloak",
    jpName: "賢者の羽織り",
    description: "上質な布に魔術防御の魔法が丹念に呪い込まれた、神秘的な外套。",
    type: "armor",
    cost: 2600,
    attackBonus: 0,
    magicBonus: 26,
    defenseBonus: 34,
  },
  {
    id: "knight_alloy_armor",
    name: "Knight Alloy Armor",
    jpName: "合金製重装アーマー",
    description: "最新の鋳造合金で作られた騎士用鎧。圧倒的な物理防護性能を約束する。",
    type: "armor",
    cost: 4200,
    attackBonus: 8,
    magicBonus: 0,
    defenseBonus: 48,
  },
  {
    id: "dragon_scale",
    name: "Onyx Dragon Scale Mail",
    jpName: "古代竜の鱗鎧",
    description: "深淵の古竜の鱗を加工した防具。比類なき盾となる、伝説とされた硬質の鎧。",
    type: "armor",
    cost: 6800,
    attackBonus: 14,
    magicBonus: 20,
    defenseBonus: 68,
  },
  {
    id: "paladin_plate",
    name: "Paladin Plate",
    jpName: "聖騎士のフルプレート",
    description: "聖水を浴びせて魔力浄化された高純度の鎧。邪悪な敵の攻撃・魔法をすべて無効化する頑強さ。",
    type: "armor",
    cost: 10500,
    attackBonus: 0,
    magicBonus: 30,
    defenseBonus: 98,
  },
  {
    id: "starshield_suit",
    name: "Starshield Suit",
    jpName: "星河の守護霊衣",
    description: "アストラルプレーン（星幽界）のエネルギー体を物理固定した、超次元仕様の美しい防護服。",
    type: "armor",
    cost: 15000,
    attackBonus: 20,
    magicBonus: 60,
    defenseBonus: 130,
  },
  {
    id: "nemesis_shroud",
    name: "Nemesis Shroud",
    jpName: "虚空魔甲ネメシス",
    description: "ダークマター（暗黒物質）を触媒に使用、着用者のオーラと連結し受ける負のエネルギーを全て消散する極限魔甲。",
    type: "armor",
    cost: 22000,
    attackBonus: 40,
    magicBonus: 90,
    defenseBonus: 180,
  },
  {
    id: "aegis_sentinel",
    name: "Aegis Sentinel Plates",
    jpName: "天体防殻イージスセンチネル",
    description: "惑星守護シールド技術を個人用に小型固定化した伝説の機甲防殻。",
    type: "armor",
    cost: 32000,
    attackBonus: 60,
    magicBonus: 120,
    defenseBonus: 250,
  },
  {
    id: "absolute_barrier_suit",
    name: "Execution Omega Armor",
    jpName: "超重量神甲エグゼキューション",
    description: "全宇宙最高の不壊金属と反重力バリアユニットを同時融合させた、最上級の不敗機動神甲鎧。",
    type: "armor",
    cost: 50000,
    attackBonus: 100,
    magicBonus: 180,
    defenseBonus: 360,
  },
];
