import { Enemy, MagicSpell } from "../types";

export const MONSTERS: Enemy[] = [
  // --- EASY TIER ---
  {
    id: "slime",
    name: "森のスライム (Forest Slime)",
    hp: 150,
    maxHp: 150,
    attack: 24,
    defense: 10,
    magic: 14,
    description: "森の奥に潜むプルプルした巨大ゲル。油断すると押しつぶされてしまう。",
    avatarIcon: "Sparkles",
    bgGradient: "from-emerald-500/10 to-teal-800/20 border-emerald-500/40",
    difficulty: "Easy",
    behaviors: [
      {
        name: "体当たり",
        actionText: "スライムは弾んで、ものすごい勢いで体当たりしてきた！",
        type: "physical",
        damageMultiplier: 1.0,
        probability: 0.5,
      },
      {
        name: "ねばねば気泡",
        actionText: "スライムは口から粘着性のある不思議な気泡を吐き出した！",
        type: "magic",
        damageMultiplier: 1.2,
        probability: 0.3,
      },
      {
        name: "からだを膨らませる",
        actionText: "スライムは限界までからだを大きく膨らませている！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },
  {
    id: "goblin",
    name: "迷いのゴブリン (Feral Goblin)",
    hp: 170,
    maxHp: 170,
    attack: 26,
    defense: 12,
    magic: 10,
    description: "洞窟の暗がりに潜む小鬼。狡猾で素早い動きから、錆びた短剣を振るう。",
    avatarIcon: "Swords",
    bgGradient: "from-amber-600/10 to-stone-800/20 border-amber-600/40",
    difficulty: "Easy",
    behaviors: [
      {
        name: "不意打ち",
        actionText: "ゴブリンは闇から突然飛び出して、背後から切りつけてきた！",
        type: "physical",
        damageMultiplier: 1.1,
        probability: 0.5,
      },
      {
        name: "投石攻撃",
        actionText: "ゴブリンは遠くから尖った石を投げつけてきた！",
        type: "physical",
        damageMultiplier: 0.9,
        probability: 0.3,
      },
      {
        name: "不気味な笑い",
        actionText: "ゴブリンはこちらを見つめて不気味にヘラヘラと笑っている！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },
  {
    id: "bat",
    name: "狂気のオオコウモリ (Crazed Cave Bat)",
    hp: 140,
    maxHp: 140,
    attack: 22,
    defense: 8,
    magic: 16,
    description: "暗闇を自在に飛び回る吸血生物。不気味な超音波であらゆる知覚を狂わせる。",
    avatarIcon: "Wind",
    bgGradient: "from-zinc-700/10 to-neutral-900/20 border-zinc-500/45",
    difficulty: "Easy",
    behaviors: [
      {
        name: "ブラッドドレイン",
        actionText: "オオコウモリは鋭い牙で噛み付き、生気を吸い取った！",
        type: "physical",
        damageMultiplier: 1.0,
        probability: 0.5,
      },
      {
        name: "超音波ノイズ",
        actionText: "オオコウモリは耳をつんざく超音波を放ってきた！",
        type: "magic",
        damageMultiplier: 1.1,
        probability: 0.5,
      },
    ],
  },
  {
    id: "skeleton_recruit",
    name: "見習い骸骨兵 (Fledgling Skeleton)",
    hp: 190,
    maxHp: 190,
    attack: 28,
    defense: 15,
    magic: 8,
    description: "朽ち果てた墓地から召喚されたスケルトンの歩兵。不気味な骨の擦れる音が響く。",
    avatarIcon: "Skull",
    bgGradient: "from-slate-600/10 to-zinc-900/20 border-slate-500/40",
    difficulty: "Easy",
    behaviors: [
      {
        name: "錆びた大剣",
        actionText: "骸骨兵は両手で持った錆びた刃を無骨に振り下ろしてきた！",
        type: "physical",
        damageMultiplier: 1.15,
        probability: 0.6,
      },
      {
        name: "盾を構える",
        actionText: "骸骨兵はひび割れた丸盾を構えて防御姿勢に入った！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.4,
      },
    ],
  },

  // --- MEDIUM TIER ---
  {
    id: "wyvern",
    name: "氷雪のワイバーン (Frost Wyvern)",
    hp: 340,
    maxHp: 340,
    attack: 37,
    defense: 20,
    magic: 28,
    description: "永久凍土をなわばりとする氷 of 飛竜。爪にふれるとすべてが凍りつく。",
    avatarIcon: "Wind",
    bgGradient: "from-sky-500/10 to-indigo-800/20 border-sky-500/40",
    difficulty: "Medium",
    behaviors: [
      {
        name: "テイルスマッシュ",
        actionText: "ワイバーンは空中から巨大な尻尾を叩きつけてきた！",
        type: "physical",
        damageMultiplier: 1.1,
        probability: 0.4,
      },
      {
        name: "フリージング息吹",
        actionText: "ワイバーンは口から極低温の氷雪ブレスを放った！",
        type: "magic",
        damageMultiplier: 1.4,
        probability: 0.4,
      },
      {
        name: "鋭く睨む",
        actionText: "ワイバーンの氷のように冷たい眼光がこちらを射すくめた！",
        type: "buff",
        damageMultiplier: 0.6, // deals minor psychological damage/defense de-buff
        probability: 0.2,
      },
    ],
  },
  {
    id: "orc",
    name: "略奪兵オーク (Ravager Orc)",
    hp: 380,
    maxHp: 380,
    attack: 44,
    defense: 25,
    magic: 15,
    description: "強靭な肉体を持つ好戦的な蛮族。大斧による無慈悲な破壊が獲物を蹂躙する。",
    avatarIcon: "Flame",
    bgGradient: "from-red-900/10 to-stone-900/20 border-red-800/40",
    difficulty: "Medium",
    behaviors: [
      {
        name: "ブルタスク・チャージ",
        actionText: "オークは荒々しい咆哮とともに全身の体重を乗せて突進してきた！",
        type: "physical",
        damageMultiplier: 1.3,
        probability: 0.5,
      },
      {
        name: "一刀両断",
        actionText: "オークは巨大な一撃でこちらの守りを断ち切ろうとした！",
        type: "physical",
        damageMultiplier: 1.1,
        probability: 0.3,
      },
      {
        name: "怒りの雄叫び",
        actionText: "オークは血走った眼で凄まじく吠え、戦意を高めた！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },
  {
    id: "harpy",
    name: "怪鳥ハルピュイア (Siren Harpy)",
    hp: 310,
    maxHp: 310,
    attack: 35,
    defense: 20,
    magic: 32,
    description: "翼を持つ冷艶な魔獣。吹き荒れる高周波の風と美しき魔歌で聴覚と平衡を崩す。",
    avatarIcon: "Music",
    bgGradient: "from-fuchsia-600/10 to-indigo-950/20 border-fuchsia-500/40",
    difficulty: "Medium",
    behaviors: [
      {
        name: "フェザーストーム",
        actionText: "ハルピュイアは急降下しながら鋭い鋼の羽根を嵐のように降らせた！",
        type: "physical",
        damageMultiplier: 1.15,
        probability: 0.4,
      },
      {
        name: "魅惑のデスソング",
        actionText: "ハルピュイアの甘美な歌声が響く。魔力が脳に直接浸透していく！",
        type: "magic",
        damageMultiplier: 1.3,
        probability: 0.4,
      },
      {
        name: "風圧による視界奪取",
        actionText: "ハルピュイアの激しい羽ばたきが局所的な真空を作り出した！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },
  {
    id: "golem",
    name: "遺跡の魔導ゴーレム (Runic Golem)",
    hp: 430,
    maxHp: 430,
    attack: 41,
    defense: 30,
    magic: 25,
    description: "古代文明の遺跡を守護する岩石の自動兵器。ルーン文字が怪しく怪光を放つ。",
    avatarIcon: "Shield",
    bgGradient: "from-stone-600/20 to-neutral-900/30 border-stone-500/45",
    difficulty: "Medium",
    behaviors: [
      {
        name: "ヘビークラッシュ",
        actionText: "ゴーレムは岩石の巨大な拳を天井から叩落としてきた！",
        type: "physical",
        damageMultiplier: 1.25,
        probability: 0.5,
      },
      {
        name: "ルーン・バースト",
        actionText: "ゴーレムのコアから光条が収束され、魔道レーザーが放たれた！",
        type: "magic",
        damageMultiplier: 1.3,
        probability: 0.3,
      },
      {
        name: "再凝縮プロトコル",
        actionText: "ゴーレムは足元の岩を取り込んで防御装甲を再構築した！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },

  // --- HARD TIER ---
  {
    id: "dragon",
    name: "古代の守護竜 (Ancient Onyx Dragon)",
    hp: 580,
    maxHp: 580,
    attack: 52,
    defense: 28,
    magic: 44,
    description: "数千年の眠りから目覚めた漆黒 of 竜。すべてを灰にする業火をその身に宿す。",
    avatarIcon: "Flame",
    bgGradient: "from-orange-600/10 to-red-950/30 border-orange-600/40",
    difficulty: "Hard",
    behaviors: [
      {
        name: "ドラゴンスラッシュ",
        actionText: "守護竜は鋼刃のような巨大な爪で切り裂いてきた！",
        type: "physical",
        damageMultiplier: 1.2,
        probability: 0.4,
      },
      {
        name: "インフェルノブレス",
        actionText: "守護竜から全てを融解させる獄炎のブレスが噴き出した！",
        type: "magic",
        damageMultiplier: 1.6,
        probability: 0.4,
      },
      {
        name: "超高熱の咆哮",
        actionText: "ドラゴンは咆哮し、周囲の大気を熱波で包み込んだ！",
        type: "magic",
        damageMultiplier: 1.1,
        probability: 0.2,
      },
    ],
  },
  {
    id: "chimera",
    name: "狂嵐のキマイラ (Storming Chimera)",
    hp: 610,
    maxHp: 610,
    attack: 56,
    defense: 28,
    magic: 48,
    description: "獅子の頭、山羊の胴、蛇の尾を持つ伝説の魔獣。大気を切り裂き暴嵐をもたらす。",
    avatarIcon: "Sparkles",
    bgGradient: "from-yellow-600/10 to-amber-950/30 border-amber-500/40",
    difficulty: "Hard",
    behaviors: [
      {
        name: "トリプルファング",
        actionText: "キマイラの獅子と蛇が交差するように死角から同時に噛みついてきた！",
        type: "physical",
        damageMultiplier: 1.3,
        probability: 0.4,
      },
      {
        name: "サンダートランプル",
        actionText: "狂嵐のキマイラは雷鳴とともに大地を踏み鳴らし、紫電の嵐を呼んだ！",
        type: "magic",
        damageMultiplier: 1.5,
        probability: 0.4,
      },
      {
        name: "毒蛇の威嚇",
        actionText: "キマイラの尻尾である毒蛇が不快な鳴き声でこちらの動きを制限した！",
        type: "buff",
        damageMultiplier: 0.7,
        probability: 0.2,
      },
    ],
  },
  {
    id: "vampire",
    name: "吸血公爵カーミラ (Countess Carmilla)",
    hp: 560,
    maxHp: 560,
    attack: 48,
    defense: 25,
    magic: 56,
    description: "血夜を支配する不老不死の真祖。深紅に染まった薔薇と漆黒の蝙蝠を操る。",
    avatarIcon: "Heart",
    bgGradient: "from-rose-950/20 to-red-950/30 border-rose-600/40",
    difficulty: "Hard",
    behaviors: [
      {
        name: "ブラッディ・ネイル",
        actionText: "魔眼を光らせたカーミラが、影のように肉薄し、真紅の爪で引き裂いた！",
        type: "physical",
        damageMultiplier: 1.1,
        probability: 0.35,
      },
      {
        name: "ローズ・ファンタズマ",
        actionText: "カーミラの手から鋭い荊棘を纏った赤いバラの嵐が吹き荒れた！",
        type: "magic",
        damageMultiplier: 1.6,
        probability: 0.45,
      },
      {
        name: "蝙蝠への幽体化",
        actionText: "カーミラのシルエットが血霧に包まれ、無数の黒い蝙蝠となり狂騒を始めた！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },
  {
    id: "death_knight",
    name: "死霊の守護騎士 (Dread Skeleton Knight)",
    hp: 660,
    maxHp: 660,
    attack: 60,
    defense: 35,
    magic: 35,
    description: "黒鋼の鎧に囚われた暗黒の魂。生者を地獄へと誘う破滅の魔剣士。",
    avatarIcon: "Skull",
    bgGradient: "from-zinc-900 via-neutral-950/40 to-slate-900/30 border-slate-700/50",
    difficulty: "Hard",
    behaviors: [
      {
        name: "ヘル・スマッシュ",
        actionText: "騎士は漆黒の大剣に死霊の怨念を乗せ、凄まじい衝撃波を切り下ろした！",
        type: "physical",
        damageMultiplier: 1.4,
        probability: 0.5,
      },
      {
        name: "ダークマント・フレア",
        actionText: "騎士の足元から冥府のどす黒い噴炎が噴きあがり、こちらの守りを突き破る！",
        type: "magic",
        damageMultiplier: 1.3,
        probability: 0.3,
      },
      {
        name: "不死者の誇り",
        actionText: "騎士は誇り高く剣を掲げ、不気味に輝く盾の障壁を展開した！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },

  // --- NIGHTMARE TIER ---
  {
    id: "asmodeus",
    name: "獄魔大王アスモデウス (Lord Demon Asmodeus)",
    hp: 920,
    maxHp: 920,
    attack: 68,
    defense: 38,
    magic: 62,
    description: "深淵より顕現した冥界の絶対君主。生命を蝕む魔術と暗黒剣を得意とする。",
    avatarIcon: "Skull",
    bgGradient: "from-purple-900/20 to-fuchsia-950/30 border-purple-600/50",
    difficulty: "Nightmare",
    behaviors: [
      {
        name: "破滅の魔剣",
        actionText: "アスモデウスは両手の剣に邪悪な闇のオーラを纏わせて斬り下ろした！",
        type: "physical",
        damageMultiplier: 1.3,
        probability: 0.35,
      },
      {
        name: "ダークマター崩壊",
        actionText: "アスモデウスは次元の歪みから超重力の魔力球を放った！",
        type: "magic",
        damageMultiplier: 1.7,
        probability: 0.35,
      },
      {
        name: "ソウルドレイン",
        actionText: "アスモデウスは妖艶に微笑み、こちらの精神力を吸い取った！",
        type: "magic",
        damageMultiplier: 0.8,
        mpDrain: 12,
        probability: 0.2,
      },
      {
        name: "冥府の呪縛",
        actionText: "アスモデウスは冷酷に宣告を下し、プレイヤーの防御力を低下させた！",
        type: "buff",
        damageMultiplier: 0.9,
        probability: 0.1,
      },
    ],
  },
  {
    id: "behemoth",
    name: "厄災獣ベヒモス (Cataclysm Behemoth)",
    hp: 1150,
    maxHp: 1150,
    attack: 82,
    defense: 45,
    magic: 45,
    description: "世界の破滅を呼ぶ大震天獣。その太古の咆哮は雷雲を裂き、鉄壁すら粉砕する。",
    avatarIcon: "Wind",
    bgGradient: "from-amber-950 via-red-950/30 to-zinc-950 border-orange-850/50",
    difficulty: "Nightmare",
    behaviors: [
      {
        name: "天変地異アースブレイク",
        actionText: "ベヒモスの巨体から超質量の一撃が繰り出され、地底が割れて衝撃波が噴き上がった！",
        type: "physical",
        damageMultiplier: 1.5,
        probability: 0.45,
      },
      {
        name: "メテオ・ストライク",
        actionText: "ベヒモスが咆哮すると、虚空から引き寄せられた赤熱の無数の巨石が落雷のように降り注いだ！",
        type: "magic",
        damageMultiplier: 1.4,
        probability: 0.35,
      },
      {
        name: "不失転の闘気",
        actionText: "ベヒモスの心臓が脈動し、その皮膚が憤怒によって真っ赤に硬化し始めた！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },
  {
    id: "lucifer",
    name: "傲慢の主ルシファー (Fallen Angel Lucifer)",
    hp: 1050,
    maxHp: 1050,
    attack: 76,
    defense: 36,
    magic: 80,
    description: "天界より失墜せし最高位の堕天使。すべてを支配、蹂躙する冷酷王者の威厳。",
    avatarIcon: "Sparkles",
    bgGradient: "from-violet-950/35 via-rose-950/20 to-stone-950 border-violet-700/60",
    difficulty: "Nightmare",
    behaviors: [
      {
        name: "失楽園の粛清",
        actionText: "ルシファーが指先を立てると、空間全体が裂け、超高速の超物理衝撃波が全てを切り裂いた！",
        type: "physical",
        damageMultiplier: 1.35,
        probability: 0.35,
      },
      {
        name: "傲慢の終焉カタストロフ",
        actionText: "ルシファーの背後に12の黒翼が広がり、極大の暗黒魔導フレアが爆裂した！",
        type: "magic",
        damageMultiplier: 1.8,
        probability: 0.45,
      },
      {
        name: "神聖支配の光輪",
        actionText: "「跪くがいい」ルシファーは冷淡に告げ、美しい黄金と虚無の魔術障壁を張った！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },
  {
    id: "cthulhu",
    name: "星間邪神クトゥルフ (Abosolute Cthulhu)",
    hp: 1100,
    maxHp: 1100,
    attack: 75,
    defense: 46,
    magic: 70,
    description: "果てしない宇宙深層の混沌。見る者の精神を不可逆的に崩壊させる冒涜的な触手群。",
    avatarIcon: "HelpCircle",
    bgGradient: "from-teal-950/30 via-emerald-950/20 to-neutral-950 border-teal-600/50",
    difficulty: "Nightmare",
    behaviors: [
      {
        name: "終末の触手乱舞",
        actionText: "クトゥルフの粘液に覆われた巨大な触手群が、死角なき四方八方から暴風のように襲いかかった！",
        type: "physical",
        damageMultiplier: 1.3,
        probability: 0.4,
      },
      {
        name: "マインドクラッシュ",
        actionText: "クトゥルフは冒涜的な精神波を放った！狂気が脳髄を直撃する！",
        type: "magic",
        damageMultiplier: 1.7,
        probability: 0.4,
      },
      {
        name: "無貌の領域展開",
        actionText: "狂乱の非ユーグリッド星間空間が展開され、こちらの物理法則が捻じ曲げられた！",
        type: "buff",
        damageMultiplier: 0,
        probability: 0.2,
      },
    ],
  },
];

export const PLAYER_SPELLS: MagicSpell[] = [
  // 物理スキル (Physical Skills)
  {
    id: "double_slash",
    name: "二連斬り (Double Slash)",
    description: "すばやい連続攻撃。物理攻撃力依存の小連続ダメージを与える。",
    mpCost: 6,
    type: "damage",
    category: "physical",
    power: 1.35,
    color: "bg-orange-650 hover:bg-orange-700 text-white shadow-orange-650/30",
  },
  {
    id: "armor_break",
    name: "破兜撃 (Armor Break)",
    description: "兜を叩き割る重厚な一撃。敵の防御を崩し大物理ダメージを与える。",
    mpCost: 12,
    type: "damage",
    category: "physical",
    power: 1.85,
    color: "bg-red-750 hover:bg-red-800 text-white shadow-red-750/30",
  },
  {
    id: "storm_blade",
    name: "烈風撃 (Storm Blade)",
    description: "風の刃をまとう超高速の強烈な斬撃。物理最大級のダメージを与える。",
    mpCost: 18,
    type: "damage",
    category: "physical",
    power: 2.5,
    color: "bg-emerald-700 hover:bg-emerald-800 text-white shadow-emerald-700/30",
  },
  // 魔法スキル (Magical Skills)
  {
    id: "fireball",
    name: "烈火の球 (Fireball)",
    description: "魔力を炎に変換し放つ。安定した高い爆発ダメージを与える。",
    mpCost: 10,
    type: "damage",
    category: "magic",
    power: 1.5,
    color: "bg-rose-600 hover:bg-rose-700 text-white shadow-rose-600/30",
  },
  {
    id: "lightning",
    name: "迅雷の撃 (Lightning Bolt)",
    description: "天から雷を召喚する。ダメージは不安定だが急所に当たりやすい。",
    mpCost: 16,
    type: "damage",
    category: "magic",
    power: 2.2, // will have randomized range multiplier
    color: "bg-amber-500 hover:bg-amber-600 text-zinc-950 shadow-amber-500/30",
  },
  {
    id: "gigaheal",
    name: "聖なる福音 (Holy Gospel)",
    description: "豊かな生命力を呼び覚まし、自分の体力を大きく回復させる。",
    mpCost: 12,
    type: "heal",
    category: "magic",
    power: 70, // base healing amount flat
    color: "bg-sky-600 hover:bg-sky-700 text-white shadow-sky-600/30",
  },
  {
    id: "astralbarrier",
    name: "魔導の盾 (Spirit Barrier)",
    description: "魔力膜を展開し、敵に中ダメージを与えつつ、自身のHPをわずかに回復する。",
    mpCost: 14,
    type: "status",
    category: "magic",
    power: 1.0, // multiplier + 25 hp drain
    color: "bg-teal-600 hover:bg-teal-700 text-white shadow-teal-600/30",
  },
];
